Repository Agile-Waterfall/flooq, pull requests merged in 2022-03, with the labels that each got.

#18 Project Setup
  README.md
  src/api/.gitignore
  src/api/.vscode/launch.json
  src/api/.vscode/tasks.json
  src/api/Flooq.Api/Controllers/VersionController.cs
  src/api/Flooq.Api/Domain/FlooqContext.cs
  src/api/Flooq.Api/Flooq.Api.csproj
  src/api/Flooq.Api/Migrations/20220309155117_InitialCreate.Designer.cs
  src/api/Flooq.Api/Migrations/20220309155117_InitialCreate.cs
  src/api/Flooq.Api/Migrations/20220309160426_AddVersionsTable.Designer.cs
  src/api/Flooq.Api/Migrations/20220309160426_AddVersionsTable.cs
  src/api/Flooq.Api/Migrations/FlooqContextModelSnapshot.cs
  src/api/Flooq.Api/Model/DataFlow.cs
  src/api/Flooq.Api/Model/Version.cs
  src/api/Flooq.Api/Program.cs
  src/api/Flooq.Api/Properties/launchSettings.json
  src/api/Flooq.Api/appsettings.Development.json
  src/api/Flooq.Api/appsettings.json
  src/api/Flooq.Test/Flooq.Test.csproj
  src/api/Flooq.Test/UnitTest1.cs
  src/api/FlooqApi.sln
  src/api/README.md
  src/editor/.eslintrc.js
  src/editor/.gitignore
  src/editor/README.md
  src/editor/backend/README.md
  src/editor/frontend/README.md
  src/editor/next-env.d.ts
  src/editor/next.config.js
  src/editor/package-lock.json
  src/editor/package.json
  src/editor/pages/_app.tsx
  src/editor/pages/api/hello.ts
  src/editor/pages/index.tsx
  src/editor/public/favicon.ico
  src/editor/public/vercel.svg
  src/editor/spec/sample.spec.ts
  src/editor/styles/Home.module.css
  src/editor/styles/globals.css
  src/editor/tsconfig.json
  src/executor/.eslintrc.js
  src/executor/.gitignore
  src/executor/.vscode/launch.json
  src/executor/.vscode/tasks.json
  src/executor/README.md
  src/executor/package-lock.json
  src/executor/package.json
  src/executor/source/index.ts
  src/executor/spec/sample.spec.ts
  src/executor/tsconfig.json
  src/executor/tslint.json
Labels: frontend, api, executor

#31 Add docker files and adjust build workflows
  .github/workflows/ci.api.yml
  .github/workflows/ci.editor.yml
  .github/workflows/ci.executor.yml
  src/api/Dockerfile
  src/api/README.md
  src/editor/Dockerfile
  src/editor/README.md
  src/editor/assets/.gitkeep
  src/editor/next.config.js
  src/editor/tsconfig.json
  src/executor/Dockerfile
  src/executor/README.md
Labels: enhancement

#32 Feature/api/version endpoint
  .github/workflows/ci.api.yml
  src/api/.gitignore
  src/api/Flooq.Api/Controllers/VersionController.cs
  src/api/Flooq.Api/Flooq.Api.csproj
  src/api/Flooq.Api/Program.cs
  src/api/Flooq.Api/Services/IVersionService.cs
  src/api/Flooq.Api/Services/VersionService.cs
  src/api/Flooq.Test/Controllers/VersionControllerTest.cs
  src/api/Flooq.Test/Flooq.Test.csproj
  src/api/Flooq.Test/Services/VersionServiceTest.cs
  src/api/Flooq.Test/UnitTest1.cs
Labels: api

#35 Editor: Initial Layout
  .github/workflows/ci.editor.yml
  src/editor/.env
  src/editor/Dockerfile
  src/editor/components/form/input.tsx
  src/editor/components/form/select.tsx
  src/editor/components/form/textarea.tsx
  src/editor/components/graph/filter-node.tsx
  src/editor/components/graph/http-input-node.tsx
  src/editor/components/graph/http-output-node.tsx
  src/editor/components/graph/node.tsx
  src/editor/components/header.tsx
  src/editor/components/list/data-flow-list-item.tsx
  src/editor/components/list/list-item.tsx
  src/editor/components/list/list.tsx
  src/editor/components/logo.tsx
  src/editor/components/page-title.tsx
  src/editor/helper/class.ts
  src/editor/package-lock.json
  src/editor/package.json
  src/editor/pages/_app.tsx
  src/editor/pages/api/flows.json
  src/editor/pages/api/flows.tsx
  src/editor/pages/api/flows/[id].tsx
  src/editor/pages/api/hello.ts
  src/editor/pages/api/status.tsx
  src/editor/pages/developer.tsx
  src/editor/pages/flows/[id].tsx
  src/editor/pages/index.tsx
  src/editor/pages/settings.tsx
  src/editor/postcss.config.js
  src/editor/public/android-chrome-192x192.png
  src/editor/public/android-chrome-512x512.png
  src/editor/public/apple-touch-icon.png
  src/editor/public/browserconfig.xml
  src/editor/public/favicon-16x16.png
  src/editor/public/favicon-32x32.png
  src/editor/public/favicon.ico
  src/editor/public/mstile-144x144.png
  src/editor/public/mstile-150x150.png
  src/editor/public/mstile-310x150.png
  src/editor/public/mstile-310x310.png
  src/editor/public/mstile-70x70.png
  src/editor/public/safari-pinned-tab.svg
  src/editor/public/site.webmanifest
  src/editor/public/theme.js
  src/editor/public/vercel.svg
  src/editor/spec/class.spec.ts
  src/editor/spec/sample.spec.ts
  src/editor/styles/Home.module.css
  src/editor/styles/globals.scss
  src/editor/styles/settings.scss
  src/editor/styles/theme-custom.scss
  src/editor/tailwind.config.js
Labels: frontend

#34 Adding Kubernetes config
  .docker/docker-compose.yml
  .github/workflows/cd.all.yml
  .github/workflows/cd.deploy.yml
  .github/workflows/ci.api.yml
  .github/workflows/ci.editor.yml
  .github/workflows/ci.executor.yml
  .gitignore
  .helm/Chart.lock
  .helm/Chart.yaml
  .helm/README.md
  .helm/local-pv.yaml
  .helm/templates/api.deployment.yaml
  .helm/templates/api.service.yaml
  .helm/templates/editor.deployment.yaml
  .helm/templates/editor.service.yaml
  .helm/templates/executor.deployment.yaml
  .helm/templates/executor.service.yaml
  .helm/templates/ingress.yaml
  .helm/values-prod.yaml
  .helm/values-staging.yaml
  src/api/README.md
  src/editor/README.md
  src/executor/README.md
Labels: enhancement

#54 Define dataflow documentation
  docs/dataflow.md
Labels: documentation, frontend, api, executor

#36 Added call to version endpoint of api, added basic logging #20
  .github/workflows/ci.executor.yml
  .gitignore
  src/executor/.env
  src/executor/.gitignore
  src/executor/package-lock.json
  src/executor/package.json
  src/executor/source/ApiInterface.ts
  src/executor/source/Index.ts
  src/executor/source/index.ts
  src/executor/source/routes/VersionRouter.ts
  src/executor/source/utils/logging/Logger.ts
  src/executor/source/utils/logging/MorganMiddleware.ts
  src/executor/spec/ApiInterface.spec.ts
  src/executor/spec/routes/VersionRoute.spec.ts
  src/executor/spec/sample.spec.ts
Labels: enhancement, executor
